import { pageHead, status } from './components.js';

export function loginScreen(state) {
  return `<main class="auth-screen"><section class="auth-card"><div class="eyebrow">ARCHON BASE / AI BACKEND</div><h1>Sign in to your AI Backend</h1><p>Connect to your local Archon API to manage projects, vector backends, functions, models, storage, and tools.</p><form data-form="login" class="auth-form"><label>Email<input name="email" type="email" autocomplete="username" required placeholder="owner@example.com"></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label>${state.authError ? `<div class="form-error" role="alert">${state.authError}</div>` : ''}<button class="button primary" type="submit">${state.authLoading ? 'Signing in…' : 'Sign in'}</button></form><p class="form-note">Local preview: create the first account with <code>archon bootstrap-user</code>.</p></section></main>`;
}

export function liveProjects(state) {
  const projects = state.projects;
  return `${pageHead('BUILD / PROJECTS', 'Projects', 'Create and organize the backend for each AI application.', 'new-project')}<section class="panel"><div class="panel-heading"><div><h2>AI projects</h2><p>${state.projectsLoading ? 'Loading projects from the API…' : 'Projects are loaded from your authenticated Archon API.'}</p></div><span class="tag">API-BACKED</span></div>${state.projectsError ? `<div class="form-error" role="alert">${state.projectsError}</div>` : ''}${projects.length ? `<div class="live-project-list">${projects.map((project) => `<article class="live-project"><div><h3>${project.metadata?.name || 'Unnamed project'}</h3><p>${project.spec?.displayName || 'AI Backend project'} · ${project.spec?.environment || 'development'} · ${project.spec?.region || 'local'}</p></div>${status(project.status?.phase || 'Pending')}</article>`).join('')}</div>` : '<div class="empty-state"><div class="empty-mark">◇</div><h3>No projects yet</h3><p>Create your first AI Backend project to start adding vector databases, storage, functions, models, and tools.</p><button class="button primary" data-action="new-project">＋ Create project</button></div>'}</section>`;
}
